title: "Gavin Chappell"
baseURL: "https://www.gavinchappell.co.uk/"
languageCode: "en-gb"
enableGitInfo: false
enableRobotsTXT: true

params:
  author:
    name: "Gavin Chappell"
  enableSharingButtons: true
  # Metadata mostly used in document's head
  description: "Gavin Chappell"
  keywords: "homepage"
  images: [""]

languages:
  en:
    title: "Gavin Chappell"
    copyright: "Gavin Chappell"
    readOtherPosts: "Read more..."


menu:
  main:
    - identifier: "Experience"
      name: "experience"
      url: "/experience"

outputs:
  home:
    - HTML
    - JSON

taxonomies:
  tag: "tags"

module:
  imports:
    - path: 'github.com/imfing/hextra'

experience:
  - name: Cisco Systems
    startDate: "17/11/2020"
    endDate: ""
    title: "Software Engineer"
  - name: Barracuda Networks
    startDate: "1/6/2013"
    endDate: "16/11/2020"
    title: "Escalation Engineer"
