title: "Gavin Chappell"
baseURL: "https://www.gavinchappell.co.uk/"
languageCode: "en-gb"
enableGitInfo: false
enableRobotsTXT: true

params:
  author:
    name: "Gavin Chappell"
  enableSharingButtons: true
  # Metadata mostly used in document's head
  description: "Gavin Chappell"
  keywords: "homepage"
  images: [""]

languages:
  en:
    title: "Gavin Chappell"
    copyright: "Gavin Chappell"
    readOtherPosts: "Read more..."


menu:
  main:
    - identifier: "what you're reading"
      name: "what you're reading"
      url: "/what-youre-reading/"
    - identifier: "what i'm tinkering with"
      name: "what i'm tinkering with"
      url: "/homelab/"
    - identifier: "Experience"
      name: "experience"
      url: "/experience"

outputs:
  home:
    - HTML
    - JSON

taxonomies:
  tag: "tags"

module:
  imports:
    - path: 'github.com/imfing/hextra'

markup:
  goldmark:
    renderer:
      unsafe: true
