title: "Gavin Chappell"
baseURL: "https://www.gavinchappell.co.uk/"
languageCode: "en-gb"
enableGitInfo: false
enableRobotsTXT: true

author:
  name: "Gavin Chappell"
params:
  enableSharingButtons: true
  footer:
    trademark: true
    author: true
    rss: true
    topText: 
      - '<a href="mailto:gavin.chappell@protonmail.com">email</a>'
  homeSubtitle: I am a Software Engineer for a company you've definitely heard of. Here are some services I use.
  disableReadOtherPosts: false
  # Metadata mostly used in document's head
  description: "This is a website."
  keywords: "homepage"
  images: [""]
  social:
    - name: "github"
      url: "https://github.com/g-a-c"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/gavinchappell/"
    - name: "bitbucket"
      url: "https://bitbucket.org/gac/"
    - url: "https://gitlab.com/gac"
      name: "gitlab"
    - url: "https://keybase.io/gac"
      name: "keybase"

languages:
  en:
    title: "This is a website."
    copyright: "me."
    readOtherPosts: "Read more..."
    params:
      logo:
        logoText: "/home/gavin"
        logoHomeLink: "/"


menu:
  main:
    - identifier: "posts"
      name      : "posts"
      url       : "/posts"
    - identifier: "contributions"
      name      : "contributions"
      url       : "/projects/contributions"
    - identifier: "creations"
      name      : "creations"
      url       : "/projects/creations"
    

# address: "Nottingham"
# email: "gavin.chappell@protonmail.com"
# favicon: "/favicon.ico"
# firstName: "Gavin"
# lastName: "Chappell"
# #phone: "1-555-555-1234"
# profileImage: "img/profile.jpg"
# showEducation: false
# showExperience: true
# showOpenSource: true
# showProjects: true
# showPublications: true
# showQr: false
# showSkills: true

#[params.google]

#[params.google.analytics]
#trackerID: "XX-123446-01"

outputs:
  home:
    - HTML
    - JSON

taxonomies:
  tag: "tags"

module:
  imports:
    - path: 'github.com/rhazdon/hugo-theme-hello-friend-ng'
